
Turn 3
================================================================
warning: entity 1 was directed to use 20 halite to move south, but only 0 halite was available
At command 1 of 1:
>>> 1   m 1 s


Turn 5
================================================================
warning: entity 1 was directed to use 39 halite to move south, but only 37 halite was available
At command 1 of 1:
>>> 1   m 1 s


Turn 8
================================================================
error: communication error with bot: read failed, errno was: 0 (Undefined error: 0)
Last input received was:


Bot error output was:
Traceback (most recent call last):
  File "MyBot.py", line 255, in <module>
    if newShip.id == knownShip.id:
AttributeError: 'Miner' object has no attribute 'id'

